# NumPy 기본: 배열과 벡터 연산
---

In [63]:
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

- Numericla Python
- 파이썬에서 산술 계산을 위한 가장 중요한 필수 패키지
- Numpy에서 제공하는 것들
    - 효율적인 다차원 배열 ndarray는 빠른 배열 계산과 유연한 **브로드캐스팅** 기능을 제공한다.
    - 반복문을 작성할 필요 없이 전체 데이터 배열을 빠르게 계산할 수 있는 표준 수학 함수
    - 배열 데이터를 디스크에 쓰거나 읽을 수 있는 도구와 메모리에 적재된 파일을 다루는 도구
    - 선형대수, 난수 생성기, 푸리에 변환 기능
    - C, C++, 포트란으로 작성한 코드를 연결할 수 있는 C API
- NumPy 자체는 모델링이나 과학 계산을 위한 기능을 제공하지 않으므로 먼저 NumPy 배여과 배열 기반 연산에 대한 이해를 한 다음 pandas 같은 배열 기반 도구를 사용하면 더 효율적이다.
- NumPy는 대용량 데이터 배열을 효율적으로 다룰 수 있도록 설계되어 있다.
    - NumPy는 내부적으로 데이터를 다른 내장 파이썬 객체와 구분된 연속된 메모리 블록에 저장한다. NumPy의 각종 알고리즘은 모두 C로 작성되어 타입 검사나 다른 오버헤드 없이 메모리를 직접 조작할 수 있다.
    - NumPy 배열은 또한 내장 파이썬의 연속된 자료형들보다 훨씬 더 적은 메모리를 사용한다.
    - NumPy 연산은 파이썬 반복문을 사용하지 않고 전체 배열 대한 복잡한 계산을 수행할 수 있다.

- Numpy vs list

In [64]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [65]:
print("NumPy 사용시 >>> ")
%time for _ in range(10): my_arr2 = my_arr * 2
    
print(f"\nlist 사용시 >>> ")
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

NumPy 사용시 >>> 
Wall time: 23.9 ms

list 사용시 >>> 
Wall time: 1.08 s


## 4.1 NumPy ndarray: 다차원 배열 객체

ndarray는 N차원 배열 객체인데 파이썬에서 사용할 수 있는 대규모 데이터 집합을 담을 수 있는 빠르고 유연한 자료구조다. 배열은 스칼라 원소간의 연산에 사용하는 문법과 비슷한 방식을 사용해서 전체 데이터 블록에 수학적인 연산을 수행할 있다!

- 작은 배열을 만들어보자!

In [66]:
import numpy as np

# 임의의 값을 생성
# shape가 (2,3)인 랜덤 array 생성
data = np.random.randn(2, 3)
data

array([[-0.2047,  0.4789, -0.5194],
       [-0.5557,  1.9658,  1.3934]])

- 그걸 가지고 산술연산을 해보자!

In [67]:
# 모든 원소의 값에 10을 곱한다.
data * 10

array([[-2.0471,  4.7894, -5.1944],
       [-5.5573, 19.6578, 13.9341]])

In [68]:
# data 배열에서 같은 위치의 갑끼리 더한다.
data + data

array([[-0.4094,  0.9579, -1.0389],
       [-1.1115,  3.9316,  2.7868]])

- ndarray의 모든 원소는 같은 자료형이어야 한다.

In [69]:
# ndarray.shape : 배열의 각 차원의 크기를 알려주는 튜플
data.shape

(2, 3)

In [70]:
# ndarray.dtype : 배열에 저장된 자료형을 알려주는 객체
data.dtype

dtype('float64')

#### 이 장의 목표! 
- NumPy 배열을 사용하는 기초 방법을 소개
- 대체로 데이터 분석에 있어서 NumPy의 깊은 이해가 필수 사항은 아니다.
- 하지만 배열 위주의 프로그래밍과 생각하는 방법에 능숙해지는것이 파이썬을 이용한 과학 계산의 고수가 되는 지름길이다!

### 4.1.1 ndarray 생성하기

순차적인 객체를 넘겨받고, 넘겨받은 데이터가 들어 있는 새로운 NumPy 배열을 생성
```python
numpy.ndarray(shape, dtype=float, buffer=None, offset=0, strides=None, order=None)
```


- list를 사용하여 ndarray 생성

In [71]:
# 일차원 리스트 -> 일차원 배열
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [72]:
# 내부 리스트의 길이가 같은 중첩 리스트 -> 다차원 배열
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [73]:
# 다차원 배열이 생성 된 것은 차원의 수와 차원들의 모양을 확인
print(arr2.ndim) # 배열의 차원의 수
print(arr2.shape)

2
(2, 4)


- **자료형** : dtype 파라미터로 명시적으로 지정해 주지 않는 이상 자료형은 추론을 통해 고정된다.

In [74]:
print(arr1.dtype)
print(arr2.dtype)

float64
int32


- 배열 생성 함수

| 함수 | 설명 |
|:---|:---|
| array | 입력 데이터(리스트, 튜플, 배열 또는 다른 순차형 데이터)를 ndarray로 변환하며 dtype을 명시하지 않은 경우 자료형을 추론하여 저장한다. 기본적으로 입력 데이터는 복사된다.  |
| asarray | 입력 데이터를 ndarray로 변화하지만 입력 데이터가 이미 ndaray일 경우 복사가 일어나지 않는다. |
| arange | 내장 range 함수와 유사하지만 리스트대신 ndarray를 반환한다. |
| ones, ones_like | 주어진 dtype과 모양을 가지는 배영을 생성하고 내용을 모두 1로 초기화한다. ones_like는 주어진 배열과 동일한 모양과 dtype를 가지는 배열을 새로 생성하여 내용을 모두 1로 초기화한다. |
| zeros, zeros_like | ones, ones_like와 동일하지만 내용을 0으로 채운다. |
| empty, empty_like | 메모리를 할당하여 새로운 배경을 생성하지만 ones나 zeros처럼 값을 초기화하지 않는다. |
| full, full_linke | 인자로 받은 dtype과 배열의 모양을 가지는 배열을 생성하고 인자로 받은 값으로 배열을 채운다. |
| eye, identity | NxN 크기의 단위행렬을 생성한다(좌상단에서 우하단을 잇는 대각선은 1로 채워지고 나머지는 0으로 채워진다.) |

In [75]:
# 주어진 길이/모양에 0이 들어있는 배열을 생성
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [76]:
# 주어진 길이/모양에 0이 들어있는 배열을 생성
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [77]:
# 초기화 되이 않은 배열을 생성
np.empty((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [78]:
np.empty((2, 3))
# 책에 따르면 empty는 어러한 가비지 값으로 채워진 배열을 반환하는데
# 왜 np.empty((2, 3, 2))는 0으로 초기화가 되었을까?

array([[0.4094, 0.9579, 1.0389],
       [1.1115, 3.9316, 2.7868]])

In [79]:
# 파이썬 range 함수희 배열 버전
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 4.1.2 ndarray의 dtype

**dtype** ndarray가 메모리에 있는 특정 데이터를 해석하기 위해 필요한 정보(또는 **메타데이터**)를 담고 있는 특수한 객체이다.

In [82]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


- NumPy 자료형

| 자료형 | 자료형 코드 | 설명 |
|:-------|:------------|:-----|
| int8, uint8 | i1, u1 | 부호가 있는 8비트(1바이트) 정수형과 부호가 없는 8비트 정수형 |
| int16, uint16 | i2, u2 | 부호가 있는 16비트 정수형과 부호가 없는 16비트 정수형 |
| int32, uint32 | i4, u4 | 부호가 있는 32비트 정수형과 부호가 없는 32비트 정수형 |
| int34, uint64 | i8, u8 | 부호가 있는 64비트 정수형과 부호가 없는 64비트 정수형 |
| float16 | f2 | 빈정밀도 부동소수점 |
| float32 | f4 또는 f | 단정밀도 부동소수점, C언어의 float 형과 호환 |
| float64 | f8 또는 d | 배정밀도 부동소수점, C언어의 double 형과 파이썬의 float 객체와 호환 |
| float128 | f16 또는 g | 확장정밀도 부동소수점 |
| complex64,complex128, complex256 | c8, c16, c32 | 각각 2개의 32, 64, 128비트 부동소수점형을 가지는 복소수 |
| bool | ? | True와 Flase 값을 저장하는 불리언형 |
| object | 0 | 파이썬 객체형 |
| string_ | S | 고정 길이 아스키 문자열형(각 문자는 1바이트), 길이가 10인 문자열 dtype은 S10이 된다. |
| unicode_ | U | 고정 길이 유니코드형(플랫폼에 다라 문자열 바이트 수가 다르가). string_ 형과 같은 형식을 쓴다(예: U10) |

- **astype** 배열의 dtype을 명시적을 변화/캐스팅
    - 형변화 실패시 ValueError 예외가 발생
    - np.float64와 같이 명확한 형타입이 아닌 'float' 같은 문자열 입력하는 것으로도 형변환 가능

In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [9]:
float_arr = arr.astype(np.float64) # int32 -> float64
print(float_arr)
print(float_arr.dtype)

[1. 2. 3. 4. 5.]
float64


In [12]:
# float64 -> int32 : 소수점 버림
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(f'캐스팅 전 : {arr}')
print(f'캐스팅 후 : {arr.astype(np.int32)}')

캐스팅 전 : [ 3.7 -1.2 -2.6  0.5 12.9 10.1]
캐스팅 후 : [ 3 -1 -2  0 12 10]


In [15]:
# string_ -> float
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [17]:
# 다른 배열의 dtype을 이용한 형변환도 가능
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [18]:
# dtype을 사용할 수 있는 축약 코드도 존재
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([3198207760,        736, 3089090816,        736,          0,
                0,          0,          0], dtype=uint32)

### 4.1.3 NumPy 배열의 산술 연산

- **벡터화** 
    - for 문을 작성하지 않고 데이터를 일괄 처리할 수 있다.
    - 같은 크기의 배열 간의 산술 연산은 배열의 각 원소 단위로 적용된다.

In [22]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [23]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [24]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
# 스칼라 인자가 포함된 산술 연산의 경우 배열 내의 모든 원소에 스칼라 인자가 적용
print(1 / arr)
print()
print(arr ** 0.5)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [27]:
# 같은 크기를 가지는 배열 간의 비교 연산은 bool 배열을 반환한다.
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print(arr2)
arr2 > arr

[[ 0.  4.  1.]
 [ 7.  2. 12.]]


array([[False,  True, False],
       [ True, False,  True]])

- **브로드캐스팅** 크기가 다른 배열 간의 연산 -> 12장에서 다룸

### 4.1.4 색인과 슬라이싱 기초

- 1차원 배열은 표면적으로는 파이썬 리스트와 유사하게 동작

In [30]:
arr = np.arange(10)
print(f'arr : {arr}')
print(f'arr[5] : {arr[5]}') # arr에서 5번째에 있는 원소
print(f'arr[5:8] : {arr[5:8]}') # arr에서 5~7번째에 있는 원소

arr : [0 1 2 3 4 5 6 7 8 9]
arr[5] : 5
arr[5:8] : [5 6 7]


In [33]:
# 배열 조각에 스칼라 값을 대입하면
# 스칼라 값이 선택 영역 전체로 전파 된다(브로드 캐스팅)
arr[5:8] = 12 # arr에서 5~7번째에 12를 대입
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

- 리스트와의 차이점
    - 배열 조각은 원본의 **뷰**, 데이터가 복사되지 않고 조각의 변경사항이 그래로 원본에 반영된다.
    - NumPy는 대용량의 데이터 처리를 염두해 두고 설계되었기 때문에 데이터 복사가 남발되면 성능과 메모리 문제에 마주치게 될 것이다.

In [34]:
# 1. arr을 슬라이싱
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [36]:
# 2. 배열 조각의 값을 변경하고 arr을 확인
arr_slice[1] = 12345

# 배열 조각에서 변경된 내용이 원본 배열에서도 변경된 것을 확인 할 수 있음
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

- [:] 로 슬라이스하면 배열의 모든 값을 할당한다.

In [37]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

- 다차원 배열 : 0번 축 : row, 1번 축 : column

<img src="https://user-images.githubusercontent.com/16831323/125911880-286b61d6-df2c-4223-a8e6-28a8a0effa04.jpg" width=300px></img>

In [38]:
# 2차원 배열
# 색인에 해당하는 요소는 스칼라 값이 아니라 1차원 배열이다.
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [40]:
# 개별 요소 -> 재귀적으로 접근 혹은 콤마로 구분된 색인 리스트 전달
# 아래의 두개는 동일한 표현
print(arr2d[0][2])
print(arr2d[0, 2])

3
3


#

In [44]:
# 다차원 배열에서 마지막 색인을 생략하면 
# 반환되는 객체는 상위 차원의 데이터를 포함하고 
# 있는 한 차원 낮은 ndarray가 된다. 
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d)# 2x2x3 크기의 배열
print(arr3d.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [45]:
arr3d[0] # 2x3 배열

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
# arr3d[0]에는 스칼라값과 배열 모두 대입 가능!
old_values = arr3d[0].copy()

# 스칼라 대입
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [50]:
# 배열 대입
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [51]:
# (1, 0)으로 색인되는 1차원 배열
arr3d[1, 0]

array([7, 8, 9])

In [48]:
# 위의 결과는 아래와 같이 두번에 걸쳐 인덱싱한 결과와 동일하다.
x = arr3d[1]
print(x)
print()
print(x[0])

[[ 7  8  9]
 [10 11 12]]

[7 8 9]
