# 넘파이 기본 : 배열과 벡터 연산

In [1]:
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

In [2]:
%load_ext autotime

time: 182 µs (started: 2021-07-20 20:28:48 +09:00)


## 4.2 유니버설 함수 : 배열의 각 원소를 빠르게 처리하는 함수

+ 하나 이상의 스칼라값을 받아서 하나 이상의 결과값을 반환하는 간단한 함수
+ 단항 ufunc
    + sqrt 제곱급
    + exp 자연상수 e의 지수함수 값

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

time: 2.97 ms (started: 2021-07-20 20:28:48 +09:00)


In [4]:
arr = np.arange(10)
arr
np.sqrt(arr)

array([0.    , 1.    , 1.4142, 1.7321, 2.    , 2.2361, 2.4495, 2.6458,
       2.8284, 3.    ])

time: 1.73 ms (started: 2021-07-20 20:28:48 +09:00)


In [5]:
np.exp(arr)

array([   1.    ,    2.7183,    7.3891,   20.0855,   54.5982,  148.4132,
        403.4288, 1096.6332, 2980.958 , 8103.0839])

time: 1.75 ms (started: 2021-07-20 20:28:48 +09:00)


In [6]:
exp_arr = np.exp(arr)
type(exp_arr[0])

numpy.float64

time: 1.36 ms (started: 2021-07-20 20:28:48 +09:00)


+ 이항 ufunc
    + add
    + maximum

In [7]:
x = np.random.randn(8)
y = np.random.randn(8)
x

array([-0.2047,  0.4789, -0.5194, -0.5557,  1.9658,  1.3934,  0.0929,
        0.2817])

time: 1.75 ms (started: 2021-07-20 20:28:48 +09:00)


In [21]:
np.max(x) # 배열 내에서 Max

1.9657805725027142

time: 1.55 ms (started: 2021-07-20 20:28:57 +09:00)


In [9]:
y

array([ 0.769 ,  1.2464,  1.0072, -1.2962,  0.275 ,  0.2289,  1.3529,
        0.8864])

time: 1.39 ms (started: 2021-07-20 20:28:48 +09:00)


In [10]:
np.maximum(x, y)

array([ 0.769 ,  1.2464,  1.0072, -0.5557,  1.9658,  1.3934,  1.3529,
        0.8864])

time: 1.43 ms (started: 2021-07-20 20:28:48 +09:00)


+ divmod(a, b)
: 매개변수로 받은 a를 b로 나눈다. 그리고 그 몫과 나머지를 튜플(tuple) 데이터 타입으로 반환

+ modf
: 위 함수의 벡터화 버젼

In [11]:
divmod(10, 3)

(3, 1)

time: 1.37 ms (started: 2021-07-20 20:28:48 +09:00)


In [12]:
arr = np.random.randn(7) * 5
arr

array([-10.0082,  -1.8592,   8.3451,  -2.1928,  -2.6987,   2.3849,
        16.2447])

time: 1.61 ms (started: 2021-07-20 20:28:48 +09:00)


In [13]:
remainder, whole_part = np.modf(arr) # 실수를 나머지와 몫으로 (순서 주의)

time: 279 µs (started: 2021-07-20 20:28:48 +09:00)


In [14]:
remainder # 나머지 : 소수부분

array([-0.0082, -0.8592,  0.3451, -0.1928, -0.6987,  0.3849,  0.2447])

time: 1.36 ms (started: 2021-07-20 20:28:48 +09:00)


In [15]:
whole_part # 몫 : 정수부분

array([-10.,  -1.,   8.,  -2.,  -2.,   2.,  16.])

time: 1.68 ms (started: 2021-07-20 20:28:48 +09:00)


In [16]:
arr

array([-10.0082,  -1.8592,   8.3451,  -2.1928,  -2.6987,   2.3849,
        16.2447])

time: 1.8 ms (started: 2021-07-20 20:28:48 +09:00)


In [17]:
np.sqrt(arr)

/home/aiffel-dj35/anaconda3/envs/aiffel/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([   nan,    nan, 2.8888,    nan,    nan, 1.5443, 4.0305])

time: 2.63 ms (started: 2021-07-20 20:28:48 +09:00)


In [18]:
arr # 원래 arr 나오지만

array([-10.0082,  -1.8592,   8.3451,  -2.1928,  -2.6987,   2.3849,
        16.2447])

time: 1.83 ms (started: 2021-07-20 20:28:48 +09:00)


In [19]:
np.sqrt(arr, arr) # 결과 값을 arr로 지정해주면

/home/aiffel-dj35/anaconda3/envs/aiffel/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([   nan,    nan, 2.8888,    nan,    nan, 1.5443, 4.0305])

time: 1.96 ms (started: 2021-07-20 20:28:48 +09:00)


In [20]:
arr # arr 변수에 할당된 array도 아예 바뀐다.

array([   nan,    nan, 2.8888,    nan,    nan, 1.5443, 4.0305])

time: 1.4 ms (started: 2021-07-20 20:28:48 +09:00)
